### ISSUE TITLE
Running distributed lily redis reports an error, index: notify tipset: UNKNOWN: redis command error: SADD failed: i/o timeout

### ISSUE THREAD

**Issue by LINJINTIANDE** [filecoin-project/lily#983]
### Describe the bug:
Running distributed lily redis reports an error, index: notify tipset: UNKNOWN: redis command error: SADD failed: i/o timeout
config configuration：
```toml
[Queue]
 [Queue.Workers]
  [Queue.Workers.lilyWorkers]
   [Queue.Workers.lilyWorkers.RedisConfig]
        Network="tcp"
        Addr="172.16.42.30:16379"
        Username=""
        Password="lily123456@"
        PasswordEnv=""
        DB=0
        PoolSize=500
   [Queue.Workers.lilyWorkers.WorkerConfig]
        Concurrency=0
        LoggerLevel="info"
        WatchQueuePriority=5
        FillQueuePriority=3
        IndexQueuePriority=1
        WalkQueuePriority=1
        StrictPriority=false
        ShutdownTimeout=0
   [Queue.Notifiers.lilyNotifiers]
        Network="tcp"
        Addr="172.16.42.30:16379"
        Username=""
        Password="lily123456@"
        PasswordEnv=""
        DB=0
        PoolSize=500
```
        
![image](https://user-images.githubusercontent.com/42436479/172786104-1b1cad9b-d149-417c-b305-f845a11e671c.png)

**Comment by frrist** [comment]
A couple of things look incorrect here - the config indentation, lack of user name for Redis, usage of both `PasswordEnv` and `Password`. Here is what I would expect:
```toml
[Queue]
  [Queue.Workers]
    [Queue.Workers.lilyWorkers]
      [Queue.Workers.lilyWorkers.RedisConfig]
        Network = "tcp"
        Addr = "127.0.0.1:6379"
        Username = "default" <- make sure this is the correct user name for your redis instance
        Password = "lily123456" <- don't set `PasswordEnv` if this value is set
        DB = 0
        PoolSize = 500
      [Queue.Workers.lilyWorkers.WorkerConfig]
        Concurrency = 1 <- needs to be at least 1
        LoggerLevel = "info"
        WatchQueuePriority = 5
        FillQueuePriority = 3
        IndexQueuePriority = 1
        WalkQueuePriority = 1
        StrictPriority = false
        ShutdownTimeout = 30000000000
  [Queue.Notifiers]
    [Queue.Notifiers.lilyNotifiers]
      Network = "tcp"
      Addr = "127.0.0.1:6379"
      Username = "default" <- make sure this is the correct user name for your redis instance
      Password = "lily123456" <- don't set `PasswordEnv` if this value is set
      DB = 0
      PoolSize = 500
```
